ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.237
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: 'npm run prettier:files'
        language: node
        types_or: [json, ts, tsx, javascript, jsx, css]
        stages: [manual]
      - id: integrity
        name: integrity
        entry: 'npm run integrity --force'
        language: node
        stages: [push]
