name: Linux tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  linux:
    name: Linux Py${{ matrix.PYTHON_VERSION }}
    runs-on: ubuntu-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUNNER_OS: 'ubuntu'
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['2.7', '3.6', '3.7', '3.8']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install System Packages
        run: | 
          sudo apt-get update
          sudo apt-get install libegl1-mesa
      - name: Install Conda
        uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: test
           auto-update-conda: true
           auto-activate-base: false
           python-version: ${{ matrix.PYTHON_VERSION }} 
      - name: Install package dependencies
        shell: bash -l {0}
        run: conda install --file requirements/conda.txt -y -q
      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          conda install nomkl -y -q
          conda install -c spyder-ide --file requirements/tests.txt -y -q
      - name: Install pytest-mock v1
        # For some reason, pytest-mock=2 does not work with Python 2.7
        if: matrix.PYTHON_VERSION == '2.7'
        shell: bash -l {0}
        run: conda install pytest-mock=1 -y -q
      - name: Install Package
        shell: bash -l {0}
        run: pip install --no-deps -e .
      - name: Show environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: xvfb-run --auto-servernum pytest spyder_notebook --cov=spyder_notebook -x -vv
        timeout-minutes: 10
      - name: Upload coverage to Codecov
        if: matrix.PYTHON_VERSION == '3.8'
        shell: bash -l {0}
        run: codecov -t dd249610-b0a4-42f6-bcfa-e7968f836790
